package personaje;

public class Armadura {

	//ARMADURA PARA EL COMBATE
	//HACER LA BONIFICACIÓN DE CONTRA
	//PENALIZACION POR DEFENSAS ADICIONALES
	public enum TIPO_ARMADURA {FUE,DES,AGI,CON,INT,POD,VOL,PER};

}
